name: 02 - Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: "0/5 * * * *" # This is a cron expression that runs the workflow every 5 minutes.
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
